# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/infuse4g/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/infuse4g/proprietary/lib/libsecril-client.so:obj/lib/libsecrilclient.so

PRODUCT_COPY_FILES += \
    vendor/samsung/infuse4g/proprietary/vendor/firmware/bcm4330_mfg.bin:system/vendor/firmware/bcm4330_mfg.bin \
    vendor/samsung/infuse4g/proprietary/vendor/firmware/bcm4330_sta.bin:system/vendor/firmware/bcm4330_sta.bin \
    vendor/samsung/infuse4g/proprietary/bin/BCM4330B1_002.001.003.0043.0061.hcd:system/bin/BCM4330B1_002.001.003.0043.0061.hcd \
    vendor/samsung/infuse4g/proprietary/vendor/firmware/nvram_net.txt:system/vendor/firmware/nvram_net.txt \
    vendor/samsung/infuse4g/proprietary/vendor/firmware/melfas_touchkey.kcm.bin:system/vendor/firmware/melfas_touchkey.kcm.bin \
    vendor/samsung/infuse4g/proprietary/vendor/lib/hw/sensors.aries.so:system/vendor/lib/hw/sensors.aries.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libakm.so:system/vendor/lib/libakm.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libsensor_yamaha_test.so:system/vendor/lib/libsensor_yamaha_test.so \
    vendor/samsung/infuse4g/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/infuse4g/proprietary/vendor/bin/ste-cg29xx_ctrl:system/vendor/bin/ste-cg29xx_ctrl \
    vendor/samsung/infuse4g/proprietary/vendor/bin/agpsd:system/vendor/bin/agpsd \
    vendor/samsung/infuse4g/proprietary/vendor/bin/gpsd:system/vendor/bin/gpsd \
    vendor/samsung/infuse4g/proprietary/vendor/etc/gps.xml:system/vendor/etc/gps.xml \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libclientgps.so:system/vendor/lib/libclientgps.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/hw/gps.aries.so:system/vendor/lib/hw/gps.aries.so \
    vendor/samsung/infuse4g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/infuse4g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/infuse4g/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/infuse4g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libddc.so:system/vendor/lib/libddc.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libedid.so:system/vendor/lib/libedid.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/lib_tvoutengine.so:system/vendor/lib/lib_tvoutengine.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libtvout.so:system/vendor/lib/libtvout.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libtvout_jni.so:system/vendor/lib/libtvout_jni.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libtvoutfimc.so:system/vendor/lib/libtvoutfimc.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libtvouthdmi.so:system/vendor/lib/libtvouthdmi.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libtvoutservice.so:system/vendor/lib/libtvoutservice.so \
    vendor/samsung/infuse4g/proprietary/vendor/bin/tvoutserver:system/vendor/bin/tvoutserver \
    vendor/samsung/infuse4g/proprietary/vendor/bin/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    vendor/samsung/infuse4g/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/hw/gralloc.aries.so:system/vendor/lib/hw/gralloc.aries.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/samsung/infuse4g/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/samsung/infuse4g/proprietary/bin/charging_mode:system/bin/charging_mode \
    vendor/samsung/infuse4g/proprietary/bin/playlpm:system/bin/playlpm \
    vendor/samsung/infuse4g/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/infuse4g/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/infuse4g/proprietary/media/bootsamsungloop.qmg:system/media/bootsamsungloop.qmg \
    vendor/samsung/infuse4g/proprietary/media/bootsamsung.qmg:system/media/bootsamsung.qmg \
    vendor/samsung/infuse4g/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/infuse4g/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg
